3es: tes::Cone Class Reference
tes::Cone Class Reference
Defines a cone shape to display.
#include <3escone.h>
Public Member Functions
Cone (uint32_t id=0u, const V3Arg &point=V3Arg(0, 0, 0), const V3Arg &dir=DefaultDir, float angle=45.0f/360.0f *float(M_PI), float length=1.0f)
Cone (uint32_t id, uint16_t category, const V3Arg &point=V3Arg(0, 0, 0), const V3Arg &dir=DefaultDir, float angle=45.0f/360.0f *float(M_PI), float length=1.0f)
Construct a cone object.
Cone & setAngle (float angle)
Sets the cone angle at the apex (radians).
float angle () const
Get the cone angle at the apex (radians).
Cone & setLength (float length)
Set the cone length, apex to base.
float length () const
Get the cone length, apex to base.
Cone & setPoint (const V3Arg &point)
Set the position of the cone apex.
Vector3f point () const
Get the position of the cone apex.
Cone & setDirection (const V3Arg &dir)
Set the cone direction vector.
Vector3f direction () const
Get the cone direction vector.
Public Member Functions inherited from tes::Shape
Shape (uint16_t routingId, uint32_t id=0)
Shape (uint16_t routingId, uint32_t id, uint16_t category)
Construct a box object.
uint16_t routingId () const
uint32_t id () const
Shape & setId (uint32_t id)
uint16_t category () const
Shape & setCategory (uint16_t category)
Shape & setWireframe (bool wire)
Sets the wireframe flag value for this shape.
bool isWireframe () const
Returns true if the wireframe flag is set.
Shape & setTransparent (bool transparent)
Sets the transparent flag value for this shape.
bool isTransparent () const
Returns true if the transparent flag is set.
Shape & setTwoSided (bool twoSided)
Sets the two sided shader flag value for this shape.
bool isTwoSided () const
Returns true if the two sided shader flag is set.
Shape & setFlags (uint16_t flags)
Set the full set of ObjectFlag values.
uint16_t flags () const
Retrieve the full set of ObjectFlag values.
Shape & setPosition (const V3Arg &pos)
Vector3f position () const
Shape & setPosX (float p)
Shape & setPosY (float p)
Shape & setPosZ (float p)
Shape & setRotation (const QuaternionArg &rot)
Quaternionf rotation () const
Shape & setScale (const V3Arg &scale)
Vector3f scale () const
Shape & setColour (const Colour &colour)
Colour colour () const
virtual void updateFrom (const Shape &other)
Update the attributes of this shape to match other.
virtual bool writeCreate (PacketWriter &stream) const
Writes the create message to stream.
virtual int writeData (PacketWriter &stream, unsigned &progressMarker) const
Called only for complex shapes to write additional creation data.
bool writeUpdate (PacketWriter &stream) const
bool writeDestroy (PacketWriter &stream) const
virtual bool isComplex () const
Is this a complex shape? Complex shapes have writeData() called.
virtual int enumerateResources (const Resource **resources, int capacity, int fetchOffset=0) const
Enumerate the resources used by this shape.
virtual Shape * clone () const
Deep copy clone.
Static Public Attributes
static const Vector3f DefaultDir
Default direction used as a reference orientation for packing the rotation.
Additional Inherited Members
Protected Member Functions inherited from tes::Shape
void onClone (Shape *copy) const
Called when copy is created from this object to copy appropriate attributes to copy.
void init (uint32_t id, uint16_t cat=0, uint16_t flags=0)
Protected Attributes inherited from tes::Shape
uint16_t _routingId
CreateMessage _data
Detailed Description
Defines a cone shape to display.
A cone is defined by:
Component Description
point() The cone apex position. Alias for position().
direction() The direction from the apex the cone flanges out.
length() Scaling value for the arrow. Defines the true length when direction() is unit length.
angle() Angle cone axis to the walls at the apex.
Constructor & Destructor Documentation
Cone()
tes::Cone::Cone (uint32_t id, uint16_t category, const V3Arg & point = V3Arg(0, 0, 0), const V3Arg & dir = DefaultDir, float angle = 45.0f / 360.0f * float(M_PI), float length = 1.0f) inline
Construct a cone object.
Parameters
id The shape ID, unique among Cone objects, or zero for a transient shape.
category The category grouping for the shape used for filtering.
point Defines the cone apex.
dir Cone direction.
angle Angle from cone axis to walls at the apex (radians).
length Length of the cone from apex to base.
References setAngle(), setDirection(), and setLength().
Member Function Documentation
angle()
float tes::Cone::angle () const inline
Get the cone angle at the apex (radians).
Returns
The cone angle (radians).
References tes::Vector3< T >::x.
Referenced by setLength().
direction()
Vector3f tes::Cone::direction () const inline
Get the cone direction vector.
May not exactly match the axis given via setDirection() as the direction is defined by the quaternion rotation().
Returns
The arrow direction vector.
References DefaultDir.
length()
float tes::Cone::length () const inline
Get the cone length, apex to base.
Returns
The cone length.
Referenced by setLength().
point()
Vector3f tes::Cone::point () const inline
Get the position of the cone apex.
Returns
point The apex coordinate.
setAngle()
Cone & tes::Cone::setAngle (float angle) inline
Sets the cone angle at the apex (radians).
Parameters
angle The angle to set (radians).
Returns
*this
References tes::Vector3< T >::x.
Referenced by Cone(), and setLength().
setDirection()
Cone & tes::Cone::setDirection (const V3Arg & dir) inline
Set the cone direction vector.
Parameters
direction The direction vector to set. Must be unit length.
Returns
*this
References tes::Vector3< T >::axisx, tes::Vector3< T >::dot(), tes::Quaternion< T >::setAxisAngle(), and tes::V3Arg::v3.
Referenced by Cone().
setLength()
Cone & tes::Cone::setLength (float length) inline
Set the cone length, apex to base.
Parameters
length The length to set.
Returns
*this
References angle(), tes::CreateMessage::attributes, length(), tes::ObjectAttributes::scale, and setAngle().
Referenced by Cone().
setPoint()
Cone & tes::Cone::setPoint (const V3Arg & point) inline
Set the position of the cone apex.
Parameters
point The apex coordinate.
Returns
*this
Member Data Documentation
DefaultDir
const Vector3f tes::Cone::DefaultDir static
Default direction used as a reference orientation for packing the rotation.
The rotation() value is relative to this vector.
The default is (0, 0, 1)
Referenced by direction().
The documentation for this class was generated from the following file:
3escone.h