3es: tes::Arrow Class Reference
tes::Arrow Class Reference
Defines an arrow shape to display.
#include <3esarrow.h>
Public Member Functions
Arrow (uint32_t id=0u, const V3Arg &origin=V3Arg(0, 0, 0), const V3Arg &dir=DefaultDirection, float length=1.0f, float radius=0.025f)
Arrow (uint32_t id, uint16_t category, const V3Arg &origin=V3Arg(0, 0, 0), const V3Arg &dir=V3Arg(0, 0, 1), float length=1.0f, float radius=0.025f)
Construct an arrow object.
Arrow & setRadius (float radius)
Set the arrow radius.
float radius () const
Get the arrow radius.
Arrow & setLength (float length)
Set the arrow length from base to tip.
float length () const
Get the arrow length from base to tip.
Arrow & setOrigin (const V3Arg &origin)
Set the arrow origin.
Vector3f origin () const
Get the arrow base position.
Arrow & setDirection (const V3Arg &direction)
Set the arrow direction vector.
Vector3f direction () const
Get the arrow direction vector.
Public Member Functions inherited from tes::Shape
Shape (uint16_t routingId, uint32_t id=0)
Shape (uint16_t routingId, uint32_t id, uint16_t category)
Construct a box object.
uint16_t routingId () const
uint32_t id () const
Shape & setId (uint32_t id)
uint16_t category () const
Shape & setCategory (uint16_t category)
Shape & setWireframe (bool wire)
Sets the wireframe flag value for this shape.
bool isWireframe () const
Returns true if the wireframe flag is set.
Shape & setTransparent (bool transparent)
Sets the transparent flag value for this shape.
bool isTransparent () const
Returns true if the transparent flag is set.
Shape & setTwoSided (bool twoSided)
Sets the two sided shader flag value for this shape.
bool isTwoSided () const
Returns true if the two sided shader flag is set.
Shape & setFlags (uint16_t flags)
Set the full set of ObjectFlag values.
uint16_t flags () const
Retrieve the full set of ObjectFlag values.
Shape & setPosition (const V3Arg &pos)
Vector3f position () const
Shape & setPosX (float p)
Shape & setPosY (float p)
Shape & setPosZ (float p)
Shape & setRotation (const QuaternionArg &rot)
Quaternionf rotation () const
Shape & setScale (const V3Arg &scale)
Vector3f scale () const
Shape & setColour (const Colour &colour)
Colour colour () const
virtual void updateFrom (const Shape &other)
Update the attributes of this shape to match other.
virtual bool writeCreate (PacketWriter &stream) const
Writes the create message to stream.
virtual int writeData (PacketWriter &stream, unsigned &progressMarker) const
Called only for complex shapes to write additional creation data.
bool writeUpdate (PacketWriter &stream) const
bool writeDestroy (PacketWriter &stream) const
virtual bool isComplex () const
Is this a complex shape? Complex shapes have writeData() called.
virtual int enumerateResources (const Resource **resources, int capacity, int fetchOffset=0) const
Enumerate the resources used by this shape.
virtual Shape * clone () const
Deep copy clone.
Static Public Attributes
static const Vector3f DefaultDirection
Default direction used as a reference orientation for packing the rotation.
Additional Inherited Members
Protected Member Functions inherited from tes::Shape
void onClone (Shape *copy) const
Called when copy is created from this object to copy appropriate attributes to copy.
void init (uint32_t id, uint16_t cat=0, uint16_t flags=0)
Protected Attributes inherited from tes::Shape
uint16_t _routingId
CreateMessage _data
Detailed Description
Defines an arrow shape to display.
An arrow is defined by:
Component Description
origin() The arrow base position. Alias for position().
direction() The arrow direction vector. Must be unit length.
length() Length of the arrow from base to tip.
radius() Radius of the arrow body. The arrow head will be slightly larger.
Constructor & Destructor Documentation
Arrow() [1/2]
tes::Arrow::Arrow (uint32_t id = 0u, const V3Arg & origin = V3Arg(0, 0, 0), const V3Arg & dir = DefaultDirection, float length = 1.0f, float radius = 0.025f) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References setDirection().
Arrow() [2/2]
tes::Arrow::Arrow (uint32_t id, uint16_t category, const V3Arg & origin = V3Arg(0, 0, 0), const V3Arg & dir = V3Arg(0, 0, 1), float length = 1.0f, float radius = 0.025f) inline
Construct an arrow object.
Parameters
id The shape ID, unique among Arrow objects, or zero for a transient shape.
category The category grouping for the shape used for filtering.
origin The start point for the array.
dir The direction vector of the arrow.
length The arrow length.
radius Radius of the arrow body.
References setDirection().
Member Function Documentation
direction()
Vector3f tes::Arrow::direction () const inline
Get the arrow direction vector.
May not exactly match the axis given via setDirection() as the direction is defined by the quaternion rotation().
Returns
The arrow direction vector.
References DefaultDirection.
length()
float tes::Arrow::length () const inline
Get the arrow length from base to tip.
Returns
The arrow length.
Referenced by setLength().
origin()
Vector3f tes::Arrow::origin () const inline
Get the arrow base position.
Note: this aliases position().
Returns
The arrow base position.
radius()
float tes::Arrow::radius () const inline
Get the arrow radius.
Defines the shaft radius, while the head flanges to a sightly larger radius.
Returns
The arrow body radius.
References tes::Vector3< T >::x.
Referenced by setRadius().
setDirection()
Arrow & tes::Arrow::setDirection (const V3Arg & direction) inline
Set the arrow direction vector.
Parameters
direction The direction vector to set. Must be unit length.
Returns
*this
References tes::Vector3< T >::axisx, tes::Vector3< T >::dot(), tes::Quaternion< T >::setAxisAngle(), and tes::V3Arg::v3.
Referenced by Arrow().
setLength()
Arrow & tes::Arrow::setLength (float length) inline
Set the arrow length from base to tip.
Parameters
length Set the length to set.
Returns
*this
References length().
setOrigin()
Arrow & tes::Arrow::setOrigin (const V3Arg & origin) inline
Set the arrow origin.
This is the arrow base position.
Note: this aliases setPosition().
Parameters
origin The arrow base position.
Returns
*this
setRadius()
Arrow & tes::Arrow::setRadius (float radius) inline
Set the arrow radius.
Parameters
radius The new arrow radius.
Returns
*this
References radius(), and tes::Vector3< T >::x.
Member Data Documentation
DefaultDirection
const Vector3f tes::Arrow::DefaultDirection static
Default direction used as a reference orientation for packing the rotation.
The rotation() value is relative to this vector.
The default is (0, 0, 1)
Referenced by direction().
The documentation for this class was generated from the following file:
3esarrow.h