3es: tes::ObjectAttributes Struct Reference
tes::ObjectAttributes Struct Reference
Contains core object attributes.
#include <3esmessages.h>
Public Member Functions
void identity ()
Set to an identity transform coloured white.
bool read (PacketReader &reader)
Read this message from reader.
bool write (PacketWriter &writer) const
Write this message to writer.
Public Attributes
uint32_t colour
Initial object colour.
float position [3]
Object position.
float rotation [4]
Object rotation (quaternion)
float scale [3]
Object scale.
Detailed Description
Contains core object attributes.
This includes details of the model transform and colour.
Member Function Documentation
read()
bool tes::ObjectAttributes::read (PacketReader & reader) inline
Read this message from reader.
Parameters
reader The data source.
Returns
True on success.
References tes::PacketReader::readArray(), and tes::PacketReader::readElement().
Referenced by tes::MeshCreateMessage::read(), tes::CreateMessage::read(), and tes::UpdateMessage::read().
write()
bool tes::ObjectAttributes::write (PacketWriter & writer) const inline
Write this message to writer.
Parameters
writer The target buffer.
Returns
True on success.
References tes::PacketWriter::writeArray(), and tes::PacketWriter::writeElement().
Referenced by tes::MeshCreateMessage::write(), tes::CreateMessage::write(), and tes::UpdateMessage::write().
The documentation for this struct was generated from the following file:
3esmessages.h