3es: tes::MeshCreateMessage Struct Reference
tes::MeshCreateMessage Struct Reference
C++ Interface » MeshResource Messages
MeshResource creation message.
#include <3esmeshmessages.h>
Public Types
enum { MessageId = MmtCreate }
ID for this message.
Public Member Functions
bool read (PacketReader &reader)
Read this message from reader.
bool write (PacketWriter &writer) const
Write this message to writer.
Public Attributes
uint32_t meshId
Mesh resource ID.
uint32_t vertexCount
Total count.
uint32_t indexCount
Total index count.
uint8_t drawType
Topology: see DrawType.
ObjectAttributes attributes
Core attributes.
Detailed Description
MeshResource creation message.
Member Function Documentation
read()
bool tes::MeshCreateMessage::read (PacketReader & reader) inline
Read this message from reader.
Parameters
reader The data source.
Returns
True on success.
References drawType, indexCount, meshId, tes::ObjectAttributes::read(), tes::PacketReader::readElement(), and vertexCount.
write()
bool tes::MeshCreateMessage::write (PacketWriter & writer) const inline
Write this message to writer.
Parameters
writer The target buffer.
Returns
True on success.
References drawType, indexCount, meshId, vertexCount, tes::ObjectAttributes::write(), and tes::PacketWriter::writeElement().
The documentation for this struct was generated from the following file:
3esmeshmessages.h